PAxNova/Portail_des_heros

app/models/universe.rb
app/models/user.rb
db/seeds.rb

Ajout de valeurs par défaut dans nos models

Default values

---

Gemfile
Gemfile.lock
config/environments/development.rb
config/storage.yml
db/migrate/20240716155322_create_active_storage_tables.active_storage.rb
db/schema.rb

Add cloudinary

---

app/assets/stylesheets/application.scss
app/assets/stylesheets/components/_content-site.scss
app/assets/stylesheets/components/_navbar.scss
app/assets/stylesheets/components/_title_page_top.scss
app/views/layouts/application.html.erb
app/views/pages/home.html.erb
app/views/shared/_navbar.html.erb
app/views/shared/_title_page_top.html.erb

Ajout de la partial title 
Ajout des différents choix dans la navbar (acceuil, tuto, créer perso...)

Front end   chartre graphique

---

app/views/pages/home.html.erb

correction home

---

app/models/tutorial.rb
app/models/universe.rb
app/models/user.rb
db/migrate/20240717125915_create_tutorials.rb
db/schema.rb
test/models/tutorial_test.rb

A vérfiier avec des tests dans rails c

creation de Tutorials

---

app/models/post.rb
db/migrate/20240717134315_remove_category_tutorial_and_user_from_posts.rb
db/schema.rb
db/seeds.rb

modification des tables + modif de la seed

---

app/assets/stylesheets/application.scss
app/assets/stylesheets/components/_lexique.scss
app/controllers/posts_controller.rb
app/views/posts/index.html.erb
app/views/posts/show.html.erb
app/views/shared/_navbar.html.erb
config/routes.rb
db/seeds.rb
test/controllers/posts_controller_test.rb

View des posts

---

app/controllers/characters_controller.rb
app/controllers/universes_controller.rb
app/views/characters/show.html.erb
app/views/universes/show.html.erb

j'ai creer les pages univers id et characters id

creation des view pour universes id et characters id

---

app/assets/stylesheets/application.scss
app/assets/stylesheets/components/_characters.scss
app/controllers/characters_controller.rb
app/views/characters/index.html.erb

Index characters

---

app/models/character.rb

toutes les variables

---

app/assets/stylesheets/application.scss
app/assets/stylesheets/characters/_index.scss
app/assets/stylesheets/characters/_show.scss
app/assets/stylesheets/components/_card_character.scss
app/assets/stylesheets/components/_index.scss
app/views/characters/show.html.erb
app/views/universes/index.html.erb

Characters

---

app/assets/stylesheets/application.scss
app/assets/stylesheets/components/_index.scss
app/assets/stylesheets/pages/_index.scss

MAJ du SCSS

---

app/controllers/characters_controller.rb
app/views/characters/edit.html.erb
app/views/characters/show.html.erb

radio button

---

app/assets/stylesheets/components/_button.scss
app/views/universes/index.html.erb

mise à jour de la couleur des bouton en fonction des univers

News buttons

---

app/views/characters/show.html.erb

modif de l'univers

---

app/assets/stylesheets/universes/_show.scss
db/data/tutorials.yml

modif CSS couleurs titres et textes

modif CSS couleurs titres et textes

---

app/assets/stylesheets/characters/_edit.scss
app/views/characters/edit.html.erb

Clean text

---

app/assets/stylesheets/components/_lexique.scss

modif du lexique

---

app/assets/stylesheets/characters/_edit.scss
app/assets/stylesheets/components/_button.scss
app/views/characters/edit.html.erb

background et boutons dynamique pour chaque univers

Background edit front

---

app/assets/stylesheets/characters/_show.scss
app/assets/stylesheets/characters/_table_in_characters.scss
app/assets/stylesheets/components/_button.scss
app/assets/stylesheets/components/_navbar.scss
app/assets/stylesheets/components/_title_page_top.scss
app/assets/stylesheets/config/_fonts.scss
app/assets/stylesheets/pages/_home.scss
app/views/pages/home.html.erb

J'appelle des variables du fichier config/_fonts.scss
Il y a maintenant 3 variables (on peut en ajouter d'autres). 
Et elles sont appelées dans tous les autres fichiers scss. 
Ne plus utiliser une font directement dans un fichier scss. Mais passer par une variable dans le fichier _fonts présent dans config. 
Cinzel pour les headers et Spectral pour le corps du texte.

Change police

---

app/views/shared/_navbar.html.erb

logout on navbar

---

app/views/characters/show.html.erb

btn  background dynamique show personnage

btn  background dynamique show personnage

---

app/javascript/controllers/character_controller.js

j'ai retirer les slider pour mettere des valeure precis que l'utilisateur peut attribuer

caracteritiques changée

---

app/assets/stylesheets/tutorials/_home.scss
app/controllers/posts_controller.rb
app/javascript/controllers/lexique_controller.js
app/views/posts/index.html.erb
db/data/improve_the_lexique.rb
db/data/lexique.yml

Create a new lexique with h3

---

Gemfile
Gemfile.lock
app/controllers/characters_controller.rb
app/jobs/generate_backstory_job.rb
app/models/character.rb
app/views/characters/show.html.erb
config/application.rb
config/prompts.yml
config/routes.rb
config/sidekiq.yml
test/jobs/generate_backstory_job_test.rb

ajouter sidekiq pour l API character

Start sidekiq

---

app/assets/stylesheets/components/_index.scss
app/assets/stylesheets/components/_off_canvas_side_bar.scss
app/javascript/application.js
app/javascript/controllers/navbar_controller.js
app/views/layouts/application.html.erb
app/views/shared/_navbar.html.erb

Off canvas sur navbar

---

app/jobs/generate_backstory_job.rb
app/jobs/image_generator_job.rb

l'image est générée après le texte

Add image to our process

---

app/assets/stylesheets/components/_loader.scss
app/controllers/characters_controller.rb
app/javascript/controllers/backstory_controller.js
app/jobs/generate_backstory_job.rb
app/views/characters/_picture.html.erb
app/views/characters/show.html.erb

Backstory background

---

app/views/characters/edit.html.erb

Progression bar
